image: python:3.9

stages:
  - create-datasset
  - test

test:
  stage: test
  variables:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

  script:
    - pip install poetry
    - poetry config virtualenvs.create false --local
    - poetry install
    - pytest tests/

crawl:

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

  stage: create-datasset

  before_script:
    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "Antonio Feregrino"

  variables:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

  script:
    - pip install poetry
    - poetry config virtualenvs.create false --local
    - poetry install
    - KAGGLE_KEY=$KAGGLE_KEY KAGGLE_USERNAME=ioexception python -m mananeras
    - git add articulos/
    - git add urls.txt
    - git status
    - git diff --quiet && git diff --staged --quiet || git commit -m 'Nuevos archivos'
    - git push http://fferegrino:${CI_ACCESS_TOKEN}@gitlab.com/thatcsharpguy/datasets/mananeras.git HEAD:main
