image: python:3.9

stages:
  - create-datasset
  - test

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - git config --global user.email "runner@gitlab.com"
  - git config --global user.name "Antonio Feregrino"
  - pip install poetry
  - poetry config virtualenvs.create false --local
  - poetry install

test:
  stage: test
  script:
    - pytest tests/

crawl:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: create-datasset
  script:
    - KAGGLE_KEY=$KAGGLE_KEY KAGGLE_USERNAME=ioexception python -m mananeras
    - git add articulos/ urls.txt
    - git commit -m 'Nuevos archivos'
    - git push http://fferegrino:${CI_ACCESS_TOKEN}@gitlab.com/thatcsharpguy/datasets/mananeras.git HEAD:main
