[tool.poetry]
name = "mananeras"
version = "0.1.4"
description = "Las conferencias mananeras del presidente de México"
authors = ["Antonio Feregrino <antonio.feregrino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.13.0"
requests = "^2.32.0"
html5lib = "^1.1"
lxml = "^6.0.0"
kaggle = "^1.7.0"
click = "^8.1"
dateparser = "^1.2.0"
playwright = "^1.55.0"
packaging = ">=24.2"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.0"
pyproject-flake8 = "^7.0.0"
pytest = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
  )/
)
'''

[tool.flake8]
max-line-length = 120
per-file-ignores = [
]
exclude = [
]

[tool.isort]
skip_glob = [
]

# Structure
default_section = "THIRDPARTY"
known_first_party = "mananeras"

# Import Style
line_length = 88
force_grid_wrap = false
use_parentheses = true
include_trailing_comma = true
combine_as_imports = true
multi_line_output = 3