name: Scrape information

on:
  workflow_dispatch:
  schedule:
  - cron: "20 19 * * *"

jobs:
  Scrape:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install --upgrade pip==22.2.2
        pip install poetry==1.1.15
        poetry config virtualenvs.create false --local
        poetry install

    - name: Execute workload
      env:
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        KAGGLE_USERNAME: ioexception
      run: python -m mananeras

    - name: Commit changes
      run: |
        git config --global user.email "antonio.feregrino+datasets@gmail.com"
        git config --global user.name "Antonio Feregrino"
        git add articulos/ urls.txt
        git diff --quiet && git diff --staged --quiet || git commit -m 'Nuevos archivos'
        git push
